# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/drew/projects/mediakhan

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/drew/projects/mediakhan

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drew/projects/mediakhan/CMakeFiles /home/drew/projects/mediakhan/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drew/projects/mediakhan/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named khan

# Build rule for target.
khan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 khan
.PHONY : khan

# fast build rule for target.
khan/fast:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/build
.PHONY : khan/fast

khan.o: khan.cpp.o
.PHONY : khan.o

# target to build an object file
khan.cpp.o:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/khan.cpp.o
.PHONY : khan.cpp.o

khan.i: khan.cpp.i
.PHONY : khan.i

# target to preprocess a source file
khan.cpp.i:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/khan.cpp.i
.PHONY : khan.cpp.i

khan.s: khan.cpp.s
.PHONY : khan.s

# target to generate assembly for a file
khan.cpp.s:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/khan.cpp.s
.PHONY : khan.cpp.s

log.o: log.cpp.o
.PHONY : log.o

# target to build an object file
log.cpp.o:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/log.cpp.o
.PHONY : log.cpp.o

log.i: log.cpp.i
.PHONY : log.i

# target to preprocess a source file
log.cpp.i:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/log.cpp.i
.PHONY : log.cpp.i

log.s: log.cpp.s
.PHONY : log.s

# target to generate assembly for a file
log.cpp.s:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/log.cpp.s
.PHONY : log.cpp.s

redis.o: redis.cpp.o
.PHONY : redis.o

# target to build an object file
redis.cpp.o:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/redis.cpp.o
.PHONY : redis.cpp.o

redis.i: redis.cpp.i
.PHONY : redis.i

# target to preprocess a source file
redis.cpp.i:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/redis.cpp.i
.PHONY : redis.cpp.i

redis.s: redis.cpp.s
.PHONY : redis.s

# target to generate assembly for a file
redis.cpp.s:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/redis.cpp.s
.PHONY : redis.cpp.s

voldemort.o: voldemort.cpp.o
.PHONY : voldemort.o

# target to build an object file
voldemort.cpp.o:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/voldemort.cpp.o
.PHONY : voldemort.cpp.o

voldemort.i: voldemort.cpp.i
.PHONY : voldemort.i

# target to preprocess a source file
voldemort.cpp.i:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/voldemort.cpp.i
.PHONY : voldemort.cpp.i

voldemort.s: voldemort.cpp.s
.PHONY : voldemort.s

# target to generate assembly for a file
voldemort.cpp.s:
	$(MAKE) -f CMakeFiles/khan.dir/build.make CMakeFiles/khan.dir/voldemort.cpp.s
.PHONY : voldemort.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... khan"
	@echo "... rebuild_cache"
	@echo "... khan.o"
	@echo "... khan.i"
	@echo "... khan.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... redis.o"
	@echo "... redis.i"
	@echo "... redis.s"
	@echo "... voldemort.o"
	@echo "... voldemort.i"
	@echo "... voldemort.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

